### ISSUE TITLE
Statamic v5 support

### ISSUE THREAD

**Issue by concept7-tools** [justkidding96/statamic-aardvark-seo#176]
What's the estimation on supporting Statamic v5?

**Comment by CandourDevs** [comment]
Hi @concept7-tools 

We are planning on upgrading the addon to the V5 release next week, and will update the community once the V5 support is live. 

Let us know if you have any other questions!

**Comment by justkidding96** [comment]
@CandourDevs It's almost the end of the week 😄 Is there an ETA yet? We would like to upgrade a number of projects to Statamic 5.

**Comment by CandourDevs** [comment]
Hi @justkidding96 , we're hoping to get this out in the next few days :)

**Comment by sstottelaar** [comment]
@CandourDevs any update on an ETA? We would like to upgrade our projects to Statamic 5 as well.

**Comment by CandourDevs** [comment]
Hi @sstottelaar , we have been reviewing the status of an upstream issue in CMS core. For now the v5 release is scheduled for this friday. Wishing you all the best

**Comment by justkidding96** [comment]
@CandourDevs Meanwhile, it is Monday. Can you give us an update on when the new version will be released? We have a dozen or so projects that we can't update right now and are therefore more than 10 Statamic core updates behind. I really appreciate your efforts but we really can't wait any longer.

**Comment by CandourDevs** [comment]
Sorry for the delay. We have now released version 5. Let us know if you have any problems.

**Comment by leganz** [comment]
We currently run into issues with timeout in combination with s3 buckets with the latest version- do we need to adapt any settings?

**Comment by CandourDevs** [comment]
@leganz Hi. Thank you for letting us know. Can you provide us with further details of the issue you’re experiencing?

**Comment by mbs-arran-baker** [comment]
Also experiencing timeout issues when using the latest version with s3 filesystem. All pages are timing out and failing to load, all pages are working when not using an s3 filesystem.

**Comment by mattmultiplied** [comment]
Same problem with the S3 filesystem, we still can't upgrade some sites to Statamic 5 due to this issue.

**Comment by davidwittenbrink** [comment]
Hi!
We were also receiving timeouts after upgrading to v5. I did some digging and found out that we had configured the project to use the `regex` parser in `config/statamic/antlers.php`. The timeout was resolved when I switched to `runtime`. Found some docs about it [here](https://statamic.dev/upgrade-guide/3-3-to-3-4#the-runtime-antlers-parser-is-the-default).

There are multiple checks for the parser in the addon, e.g. here:
https://github.com/WithCandour/statamic-aardvark-seo/blob/71cc042f7d0ad391bc85339d677451d2c2d2018a/src/Tags/AardvarkSeoTags.php#L26-L30

Still not sure what causes the problem but maybe it helps someone else as a workaround.
